included:
  - Sources
  - Tests
excluded:
  - .build
  - DerivedData
  - Pods
  - Carthage
  - vendor
  - fastlane

disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - file_length
  - type_body_length

opt_in_rules:
  - empty_count
  - empty_string
  - closure_spacing
  - contains_over_first_not_nil
  - fatal_error_message
  - force_unwrapping
  - implicitly_unwrapped_optional
  - missing_docs
  - multiline_parameters
  - vertical_parameter_alignment_on_call

analyzer_rules:
  - unused_import
  - unused_declaration

force_cast: warning
force_try: warning
force_unwrapping: warning

cyclomatic_complexity:
  warning: 15
  error: 25

identifier_name:
  min_length: 2
  excluded:
    - id
    - URL
    - vm
    - to
    - at
    - in
    - of
    - up
    - i
    - j
    - k

reporter: "xcode" 