name: Swift CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: false
        default: 'Manual build and test'

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Show Xcode version
      run: xcodebuild -version
      
    - name: Show Swift version
      run: swift --version
      
    - name: Make scripts executable
      run: |
        chmod +x scripts/*.sh
      
    - name: Build Core Package
      run: |
        cd CorePackage
        swift build -v
      
    - name: Test Core Package
      env:
        CI: true
      run: |
        cd CorePackage
        # Use --enable-test-discovery to find all tests
        # Use --sanitize=thread to help with async tests
        swift test --enable-test-discovery --sanitize=thread
      
    - name: Build App
      env:
        CI: true
      run: |
        ./scripts/build_app_bundle.sh
      
    - name: Lint Swift code
      run: |
        if command -v swiftlint &> /dev/null; then
          swiftlint
        else
          echo "SwiftLint not installed, skipping linting"
        fi
      
    - name: Archive app
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        mkdir -p build
        cd build
        # Use absolute paths to avoid tar issues
        tar -czf TMBM-app.tar.gz -C $GITHUB_WORKSPACE App -C $GITHUB_WORKSPACE/build TMBMApp.app
      
    - name: Upload build artifacts
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: TMBM-build
        path: ./build/TMBM-app.tar.gz
        retention-days: 7 